export const categoryList: any = [
  { id: 1, category: "All" },
  { id: 2, category: "Humor & Memes" },
  { id: 3, category: "Fashion & Style" },
  { id: 4, category: "Fitness" },
  { id: 5, category: "Qoutes & Texts" },
  { id: 6, category: "Luxury & Motivation" },
  { id: 7, category: "Motorcycles" },
  { id: 8, category: "Nature" },
  { id: 9, category: "Food & Nutrition" },
  { id: 10, category: "Animals" },
  { id: 11, category: "Models" },
  { id: 12, category: "Ambassadors & Influencers" },
  { id: 13, category: "Music & Singer" },
  { id: 14, category: "Art" },
  { id: 14, category: "Technology" },
  { id: 14, category: "Gaming" },
  { id: 14, category: "Entrepreneurship" },
  { id: 14, category: "Architecture & interior" },
  { id: 14, category: "Fan Accounts" },
  { id: 14, category: "celebrity" },
  { id: 14, category: "Makeup" },
  { id: 14, category: "Hair" },
  { id: 14, category: "Nails" },
  { id: 14, category: "Sports" },
  { id: 14, category: "Love & Romance" },
  { id: 14, category: "Travel" },
  { id: 14, category: "Dogs" },
  { id: 14, category: "Cats" },
];
